# Generated by Django 3.1.3 on 2020-11-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollStartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrollRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('enrollNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.enrollnumber')),
                ('enrollStartTime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.enrollstarttime')),
            ],
        ),
    ]
