# Generated by Django 3.1.3 on 2020-11-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_enrollnumber_enrollstarttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollrank',
            name='enrollStartTime',
        ),
    ]
