# Generated by Django 3.1.3 on 2020-11-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_enrollrank_enrollstarttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollrank',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
